velocity_left:
   type: 'velocity_controllers/JointVelocityController'
   joint: 'wheels_left'

velocity_right:
   type: 'velocity_controllers/JointVelocityController'
   joint: 'wheels_right'

position_left: #2015.09.23 not working: "hardware_interface::PositionJointInterface' is not registered in the hardware_interface::RobotHW class"
   type: 'position_controllers/JointPositionController'
   joint: 'wheels_left'

odom_raw: #the epos_hardware node return the position as raw data in steps (4*resolution = 2000 per revolution)
   type: 'joint_state_controller/JointStateController'
   publish_rate: 50
